eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8765
spring:
  application:
    name: service-order-feign
#######################################
##   feign客户端日志配置 
#######################################
logging:
 level:
  com.jalja.org.spring.simple.dao.FeignUserClient: DEBUG     
  
## 开启hystrix
feign:
   hystrix: 
    enabled: true  
  
###超时时间
hystrix:
   command: 
     default: 
       execution: 
        isolation:
         thread: 
          timeoutInMilliseconds: 4000  
  